---
title: "bitGPT 패키지 이해"
description: |
  **OpenAI API**를 보다 쉽게 **인터페이스**할 수 있는, 그리고 **한국어를 지원**하여 **사용성을 제고**한 bitGPT를 소개합니다.
site: distill::distill_website
author:
  - name: 유충현
    url: https://choonghyunryu.github.io
    affiliation: 한화생명, 한국R사용자회
citation_url: https://choonghyunryu.github.io/intro_Rpackages/bitGPT
# bibliography: biblio.bib
date: 2023-04-13 
output:
  distill::distill_article:
    self_contained: false  
    toc: true
    toc_depth: 3 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      collapse = FALSE,
                      fig.align = "center")
library(shiny)
library(htmltools)
library(emo)
xaringanExtra::use_panelset()
```

```{r, echo=FALSE, eval=TRUE}
p(align = "middle",
  img(src = "img/gogh_01.png", width = "25%"),
  img(src = "img/gogh_02.png",  width = "25%")
)
```

```{r, preface, echo=FALSE}
div(class = "preface", 
    h4("들어가기"),
    "chatGPT를 인터페이스한 R 패키지 중에 하나입니다.", br(),
    "그러나 한국 R사용자가 좀 더 편리하게 사용할 수 있는 방법을 고민했습니다.", br(),
    "여러분의 피드백을 염두에 둔 오늘 소개를 통해서 좀더 발전할 수 있는 기회가 되었으면 합니다.")
```

# 리소스

## 패키지 리파지토리

현재는 [Github](https://github.com/bit2r/bitGPT){target="_blank"} 리파지토리에서 패키지를 제공하고 있습니다.

## 패키지 홈페이지

- [bitGPT](https://r2bit.com/bitGPT/){target="_blank"}

## 소개 슬라이드

- [R과 함께 chatGPT 활용하기](https://choonghyunryu.github.io/intro_Rpackages/slide/slide_bitGPT/){target="_blank"}


## bitGPT로 개발한 Shiny 앱

- [shinyGPT](https://github.com/choonghyunryu/shinyGPT/){target="_blank"}





